In [79]:
import numpy as np
import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

# **now train image & train lebels will be defined**

In [80]:
train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

In [81]:
print(train_images.shape)
print(train_labels.shape)
print(test_images.shape)
print(test_labels.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


# **normalize the data into -0.5 to 0.5**

In [82]:
train_images= (train_images/255)- 0.5
test_images =(test_images/255)-0.5

In [83]:
train_images[0]

array([[-0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       ],
       [-0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       ],
       [-0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5   

In [84]:
print(train_images)
print(test_images)

[[[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 ...

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5

# **Reshaping the model**

In [85]:
train_images = np.expand_dims(train_images, axis=3)
test_images = np.expand_dims(test_images, axis=3)

# **parameters**

In [86]:
num_filters =10
filter_size =3
pool_size =2

# Building the model

In [87]:
model = Sequential([
  Conv2D(
    num_filters,
    filter_size,
    input_shape=(28, 28, 1),
    strides=2,
    padding='same',
    activation='relu',
  ),
  MaxPooling2D(pool_size=pool_size),
   Dropout(0.5),
  Flatten(),
  Dense(10, activation='softmax'),
])

# model **compiling**

In [88]:
model.compile('adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'],
              )

In [89]:
model.fit(
    train_images,
    to_categorical(train_labels),
    epochs=3, 
    validation_data= (test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 9s 4ms/step - loss: 0.6721 - accuracy: 0.7910 - val_loss: 0.2446 - val_accuracy: 0.9351
Epoch 2/3
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3656 - accuracy: 0.8863 - val_loss: 0.1854 - val_accuracy: 0.9503
Epoch 3/3
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3191 - accuracy: 0.9005 - val_loss: 0.1557 - val_accuracy: 0.9582


## **Predictions**

In [90]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
[7 2 1 0 4]
